#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    script for env PYTHONSTARTUP
    pip install rich
"""
import os
import sys

from rich.traceback import install
tb=install()
from rich import get_console
from rich import inspect as rich_inspect
from rich.pretty import Pretty

def inspect(*objects):
    rich_inspect(*objects, methods=True, private=True, dunder=True, sort=False)


def print(*objects, sep=" ", end="\n", file=None, flush= False):
    from rich.console import Console

    write_console = get_console() if file is None else Console(file=file)
    if type(*objects) == str:
        return write_console.print('[bold green]%s' % objects, sep=sep, end=end)
    return write_console.print(Pretty(*objects, expand_all=True), sep=sep, end=end)

class PromptPs(object):
    """
        manage PromptPs
    """
    def __init__(self, prt, env):
        self._prt = prt
        self._env = env
        self.count = 0

    def __str__(self):
        self.count = self.count + 1
        print('[bold #FFA500]%s%d%s' % (self._env, self.count, self._prt), end="")
        return None


class PromptPsSpace(object):
    """
        manage space of PromptPs
    """
    def __init__(self, ps, env):
        self._ps = ps
        self._env = env

    def __str__(self):
        return self._env + '.' * (len(str(self._ps.count)) + len(self._ps._prt))

# Environnement virtuel
env = os.environ.get('VIRTUAL_ENV')
if env:
    env_name = '(%s) ' % os.path.basename(env)
    print("\nVirtualenv '{}' contains:".format(env_name))
    print(', '.join(sorted([dist.project_name for dist in pip.get_installed_distributions()])) + '\n')
else:
    env_name = ''

sys.ps1 = PromptPs(' >>', env_name)
sys.ps2 = PromptPsSpace(sys.ps1, env_name)


class Cls(object):
    """
        clear Terminal
    """
    def __repr__(self):
        sys.ps1.count = 0
        os.system('cls' if os.name == 'nt' else 'clear')
        return ''

cls = Cls()


class Clear(object):
    """
        clear Terminal
    """
    def __repr__(self):
        sys.ps1.count = 0
        os.system('cls' if os.name == 'nt' else 'clear')
        return ''

clear = Clear()

# for linux
try:
    import readline
except ImportError:
    # print "Module readline not available."
    pass
else:
    try:
        # tabulation support
        import rlcompleter

        class TabCompleter(rlcompleter.Completer):
            """
                Completer that supports indenting
            """
            def complete(self, text, state):
                if not text:
                    return ('    ', None)[state]
                else:
                    return rlcompleter.Completer.complete(self, text, state)

        readline.set_completer(TabCompleter().complete)
        readline.parse_and_bind("tab: complete")
    except:
        pass
